services:
  mongodb:
    image: mongo:latest
    container_name: vaultx-mongo
    volumes:
      - /home/ubuntu/vaultx-data/mongodb:/data/db # Permanent AWS storage
    networks:
      - vaultx-net

  backend:
    build: ./backend
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - vaultx-net

  worker:
    build: ./worker
    restart: always
    env_file: .env
    depends_on:
      - mongodb
    networks:
      - vaultx-net

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - vaultx-net

networks:
  vaultx-net:
    driver: bridge